name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  gem_build:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: "Gem build (Ruby ${{ matrix.ruby_version }})"
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
        - 2.7
        - 3.3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Build gem
        run:  bundle exec gem build test.gemspec
